const actionTypes = {
    FETCH_USER: 'FETCH_USER',
    FETCH_USER_SUCCESS: 'FETCH_USER_SUCCESS',
    FETCH_USER_FAILURE: 'FETCH_USER_FAILURE',

    FETCH_REPOS: 'FETCH_REPOS',
    FETCH_REPOS_SUCCESS: 'FETCH_REPOS_SUCCESS',
    FETCH_REPOS_FAILURE: 'FETCH_REPOS_FAILURE',

    SELECT_REPO: 'SELECT_REPO',
    RESET_SELECTED_REPO: 'RESET_SELECTED_REPO',

    DISMISS_ERROR: 'DISMISS_ERROR',
};

export default actionTypes;
